In [41]:
import pandas as pd
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import display

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [26]:
#LECTURA DE DATOS
DATA_DIR = Path("..") / "Data"
TA={}
for f in sorted(DATA_DIR.glob("TransparenciaActiva_*.csv")):
    fecha = f.stem.split("_")[-1]                  # "2026-08"
    nombre = f"TA_{fecha[2:4]}_{fecha[5:7]}"       # "TA_26_08"
    df = (
        pd.read_csv(f, sep=";", encoding="latin-1")
          .rename(columns={"Unnamed: 0": "ID"})
    )
    globals()[nombre] = df
    TA[nombre] = df
    print(nombre, df.shape)

TA_24_09 (1781, 22)
TA_24_10 (1799, 22)
TA_24_11 (1798, 22)
TA_24_12 (1803, 22)
TA_25_01 (1825, 22)
TA_25_02 (1842, 22)
TA_25_03 (1845, 22)
TA_25_04 (1861, 22)
TA_25_05 (1874, 22)
TA_25_06 (1870, 22)
TA_25_07 (1872, 22)
TA_25_08 (1884, 22)
TA_25_09 (1878, 22)
TA_25_10 (1882, 22)
TA_25_11 (1919, 22)
TA_25_12 (1918, 22)
TA_26_01 (1907, 22)
TA_26_02 (1951, 22)
TA_26_03 (1908, 22)
TA_26_04 (1903, 22)
TA_26_05 (1886, 22)
TA_26_06 (1865, 22)
TA_26_07 (1857, 22)
TA_26_08 (1849, 22)

In [43]:
for i in TA:
    display(TA[i].head(3))

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2024,Septiembre,Auxiliar,"ABAITUA PIZARRO, GABRIEL ANTONIO",Chofer,20,AUXILIAR,Región Metropolitana de Santiago,(01),$ 838.003,$ 716.877,$ 0,$ 0,Sí,"$ 87.086 : 24,00 hrs",No tiene,No tiene,01/01/2024,31/12/2024,No informa,DIRECCION DE SERVICIO - REMUNERACION +BONO MEN...,NaN
1,2024,Septiembre,Técnico,"ABARCA MATURANA, ARMANDO IVAN",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(01),$ 779.837,$ 564.066,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/09/2024,30/09/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
2,2024,Septiembre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.404.046,$ 1.869.045,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2024,Octubre,Auxiliar,"ABAITUA PIZARRO, GABRIEL ANTONIO",Chofer,20,AUXILIAR,Región Metropolitana de Santiago,(01),$ 665.824,$ 544.698,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,DIRECCION DE SERVICIO - REMUNERACION OCTUBRE 2...,NaN
1,2024,Octubre,Técnico,"ABARCA MATURANA, ARMANDO IVAN",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(01),$ 580.971,$ 404.240,$ 0,$ 0,Sí,No tiene,"$ 168.330 : 100,00 hrs",No tiene,01/10/2024,31/10/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
2,2024,Octubre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",PROFESIONAL,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.344.975,$ 1.810.082,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2024,Noviembre,Técnico,"ABARCA MATURANA, ARMANDO IVAN",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(01),$ 494.333,$ 311.687,$ 0,$ 0,Sí,No tiene,"$ 38.257 : 22,00 hrs",No tiene,01/11/2024,30/11/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
1,2024,Noviembre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",PROFESIONAL,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.344.975,$ 1.594.424,$ 0,$ 208.521,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
2,2024,Noviembre,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 760.382,$ 570.791,$ 0,$ 208.521,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2024,Diciembre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",PROFESIONAL,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.344.975,$ 1.487.198,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PRE-HOSPITALA...,NaN
1,2024,Diciembre,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 760.382,$ 570.791,$ 0,$ 94.920,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PRE-HOSPITALA...,NaN
2,2024,Diciembre,Técnico,"ABARCA RUBIO, FERNANDA DANIELA",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 955.017,$ 420.032,$ 0,$ 112.666,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PRE-HOSPITALA...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Enero,Auxiliar,"ABAITUA PIZARRO, GABRIEL ANTONIO",Chofer,20,AUXILIAR,Región Metropolitana de Santiago,(01),$ 859.749,$ 799.087,-,$ 0,Sí,"$ 93.437 : 25,00 hrs",No tiene,No tiene,01/01/2025,14/01/2025,$ 0,REMUNERACION 01 AL 14 ENERO 2025+ BONO MENSUAL...,NaN
1,2025,Enero,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.514.657,$ 1.737.516,-,$ 235.984,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,$ 0,REMUNERACION ENE.2025+CANCELA BONO VACACIONES ...,NaN
2,2025,Enero,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 815.406,$ 612.501,-,$ 430.071,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,$ 0,REMUNERACION ENE.2025+CANCELA BONO VACACIONES ...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Febrero,Auxiliar,"ABAITUA PIZARRO, GABRIEL ANTONIO",Apoyo Administrativo,20,Chofer,Región Metropolitana de Santiago,(01),$ 60.517,$ 60.517,$ 0,$ 0,Sí,"$ 60.517 : 16,00 hrs",No tiene,No tiene,01/01/2025,14/01/2025,No informa,Sin observaciones,NaN
1,2025,Febrero,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.444.308,$ 1.683.112,$ 0,$ 152.157,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION FEB.2025,NaN
2,2025,Febrero,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 792.593,$ 614.097,$ 0,$ 98.941,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION FEB.2025,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Marzo,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.444.308,$ 1.683.512,$ 0,$ 152.157,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION MAR.2025+CANCELA PAGO TRIMESTRAL ...,NaN
1,2025,Marzo,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 792.593,$ 614.097,$ 0,$ 98.941,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION MAR.2025+CANCELA PAGO TRIMESTRAL ...,NaN
2,2025,Marzo,Técnico,"ABARCA RUBIO, FERNANDA DANIELA",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 995.470,$ 475.013,$ 0,$ 117.438,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION MAR.2025+CANCELA PAGO TRIMESTRAL ...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Abril,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.444.308,$ 1.671.199,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION ABR.2025,NaN
1,2025,Abril,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 792.593,$ 614.097,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION ABR.2025,NaN
2,2025,Abril,Técnico,"ABARCA RUBIO, FERNANDA DANIELA",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 1.057.470,$ 524.012,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION ABR.2025+ASIG. ESPECIAL TECNICA P...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Mayo,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.444.308,$ 1.633.164,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION MAY.2025,NaN
1,2025,Mayo,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 792.593,$ 614.097,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION MAY.2025,NaN
2,2025,Mayo,Técnico,"ABARCA RUBIO, FERNANDA DANIELA",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 1.401.900,$ 863.849,$ 0,$ 0,Sí,"$ 50.734 : 15,00 hrs","$ 324.696 : 80,00 hrs",No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION MAY.2025,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Junio,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.459.951,$ 1.988.942,$ 0,$ 152.483,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION JUN.2025+PAGO TRIMESTRAL LEY 19.9...,NaN
1,2025,Junio,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 797.665,$ 850.818,$ 0,$ 99.152,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION JUN.2025+PAGO TRIMESTRAL LEY 19.4...,NaN
2,2025,Junio,Técnico,"ABARCA RUBIO, FERNANDA DANIELA",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 1.674.243,$ 1.390.180,$ 0,$ 158.576,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION JUN.2025+BONO ESCOLAR CUOTA 03/20...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Julio,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.459.951,$ 1.557.962,$ 0,$ 153.131,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION JUL.2025,NaN
1,2025,Julio,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(203)(186)(205)(203)(204)(186),$ 809.757,$ 627.535,$ 0,$ 99.574,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION JUL.2025+PAGO DIF. BIENIOS JUN.2025,NaN
2,2025,Julio,Técnico,"ABARCA RUBIO, FERNANDA DANIELA",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 1.459.004,$ 834.419,$ 0,$ 118.189,Sí,"$ 54.462 : 16,00 hrs","$ 371.704 : 91,00 hrs",No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION JUL.2025,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Agosto,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.462.453,$ 1.195.473,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/08/2025,31/10/2025,No informa,Sin observaciones,NaN
1,2025,Agosto,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.459.951,$ 1.557.813,$ 0,$ 153.131,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION AGO.2025,NaN
2,2025,Agosto,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 803.711,$ 622.797,$ 0,$ 99.574,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION AGO.2025,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Septiembre,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.462.453,$ 1.195.806,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/08/2025,31/10/2025,No informa,Sin observaciones,NaN
1,2025,Septiembre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.521.503,$ 1.619.698,$ 0,$ 153.131,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION SEP.2025+CANCELA PAGO TRIMESTRAL ...,NaN
2,2025,Septiembre,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 892.378,$ 711.464,$ 0,$ 99.574,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION SEP.2025+CANCELA PAGO TRIMESTRAL ...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Octubre,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.462.453,$ 1.196.228,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/08/2025,31/10/2025,No informa,Sin observaciones,NaN
1,2025,Octubre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.459.951,$ 1.558.146,$ 0,$ 165.273,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION OCT.2025,NaN
2,2025,Octubre,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 803.711,$ 622.797,$ 0,$ 122.529,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION OCT.2025,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Noviembre,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.462.453,$ 1.196.377,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/08/2025,31/12/2025,No informa,Sin observaciones,NaN
1,2025,Noviembre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.459.951,$ 1.900.116,$ 0,$ 384.018,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION NOV.2025+CANCELA BONO TRATO USUAR...,NaN
2,2025,Noviembre,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 803.711,$ 622.797,$ 0,$ 341.274,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION NOV.2025+CANCELA BONO TRATO USUAR...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2025,Diciembre,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.462.453,$ 1.196.377,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/08/2025,31/12/2025,No informa,Sin observaciones,NaN
1,2025,Diciembre,Auxiliar,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.459.951,$ 1.490.036,$ 0,$ 165.273,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION DIC.2025+PAGO DE AGUINALDO DICIEM...,NaN
2,2025,Diciembre,Técnico,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 803.711,$ 622.797,$ 0,$ 122.529,No,No tiene,No tiene,No tiene,01/01/2025,31/12/2025,No informa,REMUNERACION DIC.2025+PAGO DE AGUINALDO DICIEM...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Enero,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.462.453,$ 1.196.490,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/03/2026,No informa,Sin observaciones,NaN
1,2026,Enero,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.459.951,$ 1.467.989,$ 0,$ 210.794,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION ENE.2026+CANCELA BONO VACACIONES ...,NaN
2,2026,Enero,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 803.711,$ 622.797,$ 0,$ 222.781,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION ENE.2026+CANCELA BONO VACACIONES ...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Febrero,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.566.702,$ 1.282.442,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/03/2026,No informa,Sin observaciones,NaN
1,2026,Febrero,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.607.545,$ 1.570.819,$ 0,$ 237.351,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,DIF. AGUINALDO NAVIDAD+DIF. BONO VACACIONES+DI...,NaN
2,2026,Febrero,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 851.939,$ 660.526,$ 0,$ 271.624,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,DIF. AGUINALDO NAVIDAD+DIF. BONO VACACIONES+DI...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Marzo,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.491.702,$ 1.219.741,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/03/2026,No informa,Sin observaciones,NaN
1,2026,Marzo,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.509.149,$ 1.496.783,$ 0,$ 156.193,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,CANCELA PAGO TRIMESTRAL LEY 19.937 PERIODO 03/...,NaN
2,2026,Marzo,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 819.787,$ 635.354,$ 0,$ 113.579,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,CANCELA PAGO TRIMESTRAL LEY 19.490 PERIODO 03/...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Abril,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.491.702,$ 1.219.741,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,Sin observaciones,NaN
1,2026,Abril,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.509.149,$ 1.391.023,$ 0,$ 185.079,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION ABR.2026,NaN
2,2026,Abril,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 819.787,$ 635.354,$ 0,$ 114.109,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION ABR.2026,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Mayo,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.491.702,$ 1.220.118,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,Sin observaciones,NaN
1,2026,Mayo,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.509.149,$ 1.391.400,$ 0,$ 185.079,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION MAY.2026,NaN
2,2026,Mayo,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 819.787,$ 635.354,$ 0,$ 114.109,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION MAY.2026,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Junio,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.512.586,$ 1.237.162,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,Sin observaciones,NaN
1,2026,Junio,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.544.278,$ 1.418.828,$ 0,$ 185.079,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,CANCELA PAGO TRIMESTRAL LEY 19.937 PERIODO 06/...,NaN
2,2026,Junio,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 831.264,$ 644.321,$ 0,$ 114.109,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,CANCELA PAGO TRIMESTRAL LEY 19.490 Y LEY 19.93...,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Julio,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.512.586,$ 1.237.239,$ 0,-,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,Sin observaciones,NaN
1,2026,Julio,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.544.278,$ 1.418.905,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION JUL.2026,NaN
2,2026,Julio,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 831.264,$ 644.321,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION JUL.2026,NaN

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2026,Agosto,Profesional,"ABARCA IBEAS, KRISHNA BELEN",Atencion Clinica,15,ENFERMERA (O),Región Metropolitana de Santiago,(01),$ 1.512.586,$ 1.237.239,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,Sin observaciones,NaN
1,2026,Agosto,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.544.278,$ 1.447.644,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION AGO.2026,NaN
2,2026,Agosto,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 831.264,$ 591.527,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION AGO.2026,NaN

In [44]:
df=pd.concat(TA.values(), ignore_index=True)
df

,Año,Mes,Estamento,Nombre completo,Cargo o función,Grado EUS o jornada,Calificación profesional o formación,Región,Asignaciones especiales del mes (inc. en rem. bruta),"Remuneración bruta del mes (incluye bonos e incentivos, asig. especiales, horas extras)",Remuneración líquida del mes,Rem. adicionales del mes (no inc. en rem. bruta),Remuneración Bonos incentivos del mes (inc. en rem. bruta),Derecho a horas extraordinarias,Montos y horas extraordinarias diurnas del mes(inc. en rem. bruta),Montos y horas extraordinarias nocturnas del mes(inc. en rem. bruta),Montos y horas extraordinarias festivas del mes (inc. en rem. bruta),Fecha de inicio dd/mm/aa,Fecha de término dd/mm/aa,Viáticos del mes (no inc. en rem. bruta),Observaciones,Unnamed: 21
0,2024,Septiembre,Auxiliar,"ABAITUA PIZARRO, GABRIEL ANTONIO",Chofer,20,AUXILIAR,Región Metropolitana de Santiago,(01),$ 838.003,$ 716.877,$ 0,$ 0,Sí,"$ 87.086 : 24,00 hrs",No tiene,No tiene,01/01/2024,31/12/2024,No informa,DIRECCION DE SERVICIO - REMUNERACION +BONO MEN...,NaN
1,2024,Septiembre,Técnico,"ABARCA MATURANA, ARMANDO IVAN",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(01),$ 779.837,$ 564.066,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/09/2024,30/09/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
2,2024,Septiembre,Profesional,"ABARCA MUÑOZ, MARITZA DENISSE",APOYO ADMINISTRATIVO,9,ABOGADO (A),Región Metropolitana de Santiago,(01),$ 2.404.046,$ 1.869.045,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
3,2024,Septiembre,Auxiliar,"ABARCA ROJAS, MANUEL EDUARDO",CONDUCTOR,24,AUXILIAR,Región Metropolitana de Santiago,(205)(203)(204)(186),$ 845.475,$ 655.884,$ 0,$ 94.920,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
4,2024,Septiembre,Técnico,"ABARCA RUBIO, FERNANDA DANIELA",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 1.040.110,$ 503.890,$ 0,$ 112.666,No,No tiene,No tiene,No tiene,01/01/2024,31/12/2024,No informa,CENTRO METROPOLITANO DE ATENCION PREHOSPITALAR...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44772,2026,Agosto,Auxiliar,"ZUÑIGA FLORES, MARCELO PAUL",CONDUCTOR,21,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(205)(202)(204)(186),$ 1.587.591,$ 1.109.259,$ 0,$ 0,Sí,"$ 150.595 : 40,00 hrs","$ 189.749 : 42,00 hrs",No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION AGO.2026,NaN
44773,2026,Agosto,Profesional,"ZUÑIGA JARAMILLO, JONATHAN ROLANDO",Apoyo Administrativo,13,PSICOLOGO (A),Región Metropolitana de Santiago,(186),$ 1.908.175,$ 1.537.874,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,Sin observaciones,NaN
44774,2026,Agosto,Técnico,"ZUÑIGA OROZCO, ROMINA JAZMIN",ATENCION CLINICA,22,TECNICO NIVEL SUPERIOR ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 1.092.182,$ 824.661,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION AGO.2026,NaN
44775,2026,Agosto,Técnico,"ZUÑIGA RIQUELME, CLAUDIO ALBERTO",ATENCION CLINICA,22,AUXILIAR DE ENFERMERIA,Región Metropolitana de Santiago,(202)(204)(186),$ 1.316.038,$ 858.615,$ 0,$ 0,Sí,"$ 52.347 : 15,00 hrs","$ 180.073 : 43,00 hrs",No tiene,01/01/2026,31/12/2026,No informa,REMUNERACION AGO.2026,NaN
44776,2026,Agosto,Técnico,"ZUÑIGA TORRES, BARBARA ALEJANDRA",Atencion Clinica,21,TECNICO NIVEL SUPERIOR LABORATORIO CLINICO,Región Metropolitana de Santiago,(186),$ 753.080,$ 620.689,$ 0,$ 0,No,No tiene,No tiene,No tiene,01/01/2026,31/12/2026,No informa,Sin observaciones,NaN